/** Every UI string as [English, Thai]. Keeping the pair together means a key can never exist in only one language. */
export const DICT = {
  // app / auth
  'app.tagline': ['Gold POS', 'ระบบร้านทอง'],
  'login.title': ['Sign in', 'เข้าสู่ระบบ'], 'login.username': ['Username', 'ชื่อผู้ใช้'], 'login.password': ['Password', 'รหัสผ่าน'], 'login.submit': ['Sign in', 'เข้าสู่ระบบ'],
  'login.tagline': ['Buy, sell and exchange gold with confidence — stock, pawn, savings and tax documents in one place.', 'ซื้อ ขาย เปลี่ยนทองได้มั่นใจ จัดการสต็อก ขายฝาก ออมทอง และเอกสารภาษีในที่เดียว'],
  'auth.logout': ['Sign out', 'ออกจากระบบ'],
  // nav
  'nav.dashboard': ['Dashboard', 'ภาพรวม'], 'nav.pos': ['Buy · Sell · Exchange', 'ซื้อ-ขาย-เปลี่ยน'], 'nav.transactions': ['Bills', 'รายการบิล'], 'nav.stock': ['Stock', 'สต็อกทอง'],
  'nav.customers': ['Customers', 'ลูกค้า'], 'nav.pawn': ['Pawn · Sell-back', 'ขายฝาก/จำนำ'], 'nav.savings': ['Gold savings', 'ออมทอง'], 'nav.rates': ['Gold prices', 'ราคาทอง'],
  'nav.reports': ['Reports', 'รายงาน'], 'nav.settings': ['Settings', 'ตั้งค่า'], 'nav.more': ['More', 'เพิ่มเติม'],
  // roles
  'role.OWNER': ['Owner', 'เจ้าของร้าน'], 'role.MANAGER': ['Manager', 'ผู้จัดการ'], 'role.CASHIER': ['Cashier', 'แคชเชียร์'], 'role.STOCK_CLERK': ['Stock clerk', 'พนักงานสต็อก'],
  // common
  'common.add': ['Add', 'เพิ่ม'], 'common.remove': ['Remove', 'ลบ'], 'common.save': ['Save', 'บันทึก'], 'common.saved': ['Saved', 'บันทึกแล้ว'], 'common.cancel': ['Cancel', 'ยกเลิก'], 'common.edit': ['Edit', 'แก้ไข'],
  'common.search': ['Search', 'ค้นหา'], 'common.empty': ['Nothing here yet', 'ยังไม่มีข้อมูล'], 'common.loading': ['Loading…', 'กำลังโหลด…'], 'common.all': ['All', 'ทั้งหมด'],
  'common.name': ['Name', 'ชื่อ'], 'common.description': ['Description', 'รายละเอียด'], 'common.customer': ['Customer', 'ลูกค้า'], 'common.phone': ['Phone', 'โทรศัพท์'], 'common.address': ['Address', 'ที่อยู่'],
  'common.amount': ['Amount', 'จำนวนเงิน'], 'common.status': ['Status', 'สถานะ'], 'common.type': ['Type', 'ประเภท'], 'common.time': ['Time', 'เวลา'], 'common.date': ['Date', 'วันที่'],
  'common.from': ['From', 'ตั้งแต่'], 'common.to': ['To', 'ถึง'], 'common.user': ['User', 'ผู้ใช้'], 'common.pts': ['pts', 'แต้ม'], 'common.active': ['Active', 'ใช้งาน'], 'common.disabled': ['Disabled', 'ปิดใช้งาน'],
  // gold price ticker
  'rate.bar': ['Gold bar', 'ทองคำแท่ง'], 'rate.ornament': ['Ornament', 'ทองรูปพรรณ'], 'rate.buySell': ['Buy / Sell', 'รับซื้อ / ขายออก'], 'rate.none': ['No gold price set', 'ยังไม่ได้ตั้งราคาทอง'], 'rate.hint': ['Buy / Sell per baht-weight (96.5%)', 'รับซื้อ / ขายออก ต่อบาททองคำ (96.5%)'],
  // dashboard
  'dash.newSale': ['New bill', 'เปิดบิลใหม่'], 'dash.salesToday': ['Sales today (ex. VAT)', 'ยอดขายวันนี้ (ไม่รวม VAT)'], 'dash.bills': ['bill(s)', 'บิล'], 'dash.gross': ['gross', 'กำไรขั้นต้น'],
  'dash.salesMonth': ['Sales this month', 'ยอดขายเดือนนี้'], 'dash.stockValue': ['Stock value', 'มูลค่าสต็อก'], 'dash.atBuyRate': ['at current buy price', 'ตามราคารับซื้อปัจจุบัน'],
  'dash.pawnActive': ['Active pawn / sell-back', 'ขายฝาก/จำนำคงเหลือ'], 'dash.contracts': ['contracts', 'สัญญา'], 'dash.overdue': ['overdue', 'เกินกำหนด'],
  'dash.savingsLiab': ['Savings owed to customers', 'เงินออมทองค้างจ่าย'], 'dash.etax': ['Awaiting e-Tax', 'รอส่ง e-Tax'], 'dash.points': ['Points outstanding', 'แต้มคงค้าง'], 'dash.stockByPurity': ['Stock by purity', 'สต็อกตามความบริสุทธิ์'],
  // POS
  'pos.title': ['Buy · Sell · Exchange', 'ซื้อ · ขาย · เปลี่ยนทอง'], 'pos.kind.sale': ['Sale', 'ขาย'], 'pos.kind.exchange': ['Exchange', 'เปลี่ยนทอง'], 'pos.kind.buy': ['Buying gold', 'รับซื้อทอง'],
  'pos.items': ['Items in stock', 'สินค้าในสต็อก'], 'pos.scan': ['Scan or type SKU / name', 'สแกนหรือพิมพ์รหัส/ชื่อ'], 'pos.customerGold': ["Customer's gold (buy / trade-in)", 'ทองของลูกค้า (รับซื้อ/เปลี่ยน)'],
  'pos.deduction': ['Deduction %', 'หักค่าเสื่อม %'], 'pos.isBar': ['Gold bar', 'ทองคำแท่ง'], 'pos.addGold': ['Add gold', 'เพิ่มทองเก่า'], 'pos.bar': ['bar', 'แท่ง'],
  'pos.bill': ['Bill', 'บิล'], 'pos.emptyBill': ['Add items or customer gold to start a bill', 'เพิ่มสินค้าหรือทองของลูกค้าเพื่อเริ่มบิล'], 'pos.oldGold': ['Old gold', 'ทองเก่า'],
  'pos.discount': ['Discount', 'ส่วนลด'], 'pos.gold': ['Gold', 'ค่าทอง'], 'pos.making': ['Making charge', 'ค่ากำเหน็จ'], 'pos.vat': ['VAT', 'ภาษีมูลค่าเพิ่ม'],
  'pos.tradeInCredit': ['Less: old gold', 'หัก: ทองเก่า'], 'pos.customerPays': ['Customer pays', 'ลูกค้าจ่าย'], 'pos.shopPays': ['Shop pays', 'ร้านจ่าย'],
  'pos.payment': ['Payment', 'การชำระเงิน'], 'pos.addMethod': ['Split payment', 'แบ่งชำระ'], 'pos.method': ['Method', 'วิธีชำระ'], 'pos.account': ['Savings account', 'บัญชีออมทอง'],
  'pos.received': ['Received', 'รับแล้ว'], 'pos.needCustomer': ['Choose a customer — required when buying gold.', 'กรุณาเลือกลูกค้า — จำเป็นเมื่อรับซื้อทอง'],
  'pos.confirm': ['Confirm bill', 'ยืนยันบิล'], 'pos.pay': ['Pay', 'ชำระเงิน'], 'pos.saved': ['Saved', 'บันทึกแล้ว'], 'pos.doneTitle': ['Bill completed', 'ทำรายการสำเร็จ'],
  'pos.printBill': ['Print bill', 'พิมพ์บิล'], 'pos.printDoc': ['Print', 'พิมพ์'], 'pos.newBill': ['New bill', 'เปิดบิลใหม่'],
  'pos.noDocs': ['No tax document was issued. Set the company tax ID in Settings first.', 'ยังไม่ได้ออกเอกสารภาษี กรุณาตั้งค่าเลขประจำตัวผู้เสียภาษีของร้านในตั้งค่าก่อน'],
  // bills
  'tx.docNo': ['Bill no.', 'เลขที่บิล'], 'tx.cashier': ['Cashier', 'พนักงาน'], 'tx.net': ['Net', 'สุทธิ'], 'tx.documents': ['Tax documents', 'เอกสารภาษี'],
  'tx.fullInvoice': ['Full tax invoice', 'ใบกำกับภาษีเต็มรูป'], 'tx.issue': ['Issue', 'ออกเอกสาร'], 'tx.invoiceIssued': ['Invoice issued', 'ออกใบกำกับภาษีแล้ว'], 'tx.buyerName': ['Buyer name / company', 'ชื่อผู้ซื้อ / บริษัท'],
  'tx.void': ['Void bill', 'ยกเลิกบิล'], 'tx.voidReason': ['Reason', 'เหตุผล'], 'tx.voidWarn': ['Stock, points, savings and tax documents will be reversed.', 'ระบบจะคืนสต็อก แต้ม เงินออม และยกเลิกเอกสารภาษี'],
  'tx.voided': ['Bill voided', 'ยกเลิกบิลแล้ว'], 'tx.voidedBecause': ['Voided', 'ยกเลิกแล้ว เนื่องจาก'],
  // stock
  'stock.receive': ['Receive item', 'รับสินค้าเข้า'], 'stock.added': ['Item added', 'เพิ่มสินค้าแล้ว'], 'stock.items': ['Items', 'รายการสินค้า'], 'stock.weight': ['Weight (g)', 'น้ำหนัก (กรัม)'],
  'stock.purity': ['Purity', 'ความบริสุทธิ์'], 'stock.pieces': ['Pieces', 'จำนวนชิ้น'], 'stock.cost': ['Cost', 'ต้นทุน'], 'stock.source': ['Source', 'ที่มา'], 'stock.category': ['Category', 'ประเภท'],
  'stock.making': ['Making charge', 'ค่ากำเหน็จ'], 'stock.reason': ['Reason', 'เหตุผล'], 'stock.adjust': ['Update status', 'ปรับสถานะ'], 'stock.history': ['Movement history', 'ประวัติการเคลื่อนไหว'],
  // customers
  'cust.new': ['New customer', 'เพิ่มลูกค้า'], 'cust.search': ['Search name / phone / ID', 'ค้นหาชื่อ / เบอร์ / บัตร'], 'cust.member': ['Member', 'สมาชิก'], 'cust.title': ['Title', 'คำนำหน้า'],
  'cust.fullName': ['Full name', 'ชื่อ-สกุล'], 'cust.idCard': ['National ID', 'เลขบัตรประชาชน'], 'cust.id13': ['13 digits', '13 หลัก'], 'cust.birth': ['Date of birth', 'วันเกิด'],
  'cust.joinMember': ['Register as member (earn points)', 'สมัครสมาชิก (สะสมแต้ม)'], 'cust.readerHint': ['ID-card reader: a connected reader can fill this form automatically (not connected yet). You can also type the details.', 'เครื่องอ่านบัตรประชาชน: เมื่อเชื่อมต่อแล้วจะกรอกฟอร์มนี้อัตโนมัติ (ยังไม่เชื่อมต่อ) หรือกรอกเองได้'],
  'cust.fromReader': ['from card reader', 'จากเครื่องอ่านบัตร'], 'cust.points': ['Points', 'แต้มสะสม'], 'cust.rewards': ['Rewards', 'ของรางวัล'], 'cust.left': ['left', 'คงเหลือ'], 'cust.redeem': ['Redeem', 'แลก'],
  'cust.redeemed': ['Reward redeemed', 'แลกของรางวัลแล้ว'], 'cust.pointsHistory': ['Points history', 'ประวัติแต้ม'],
  // pawn
  'pawn.new': ['New contract', 'ทำสัญญาใหม่'], 'pawn.no': ['Contract no.', 'เลขที่สัญญา'], 'pawn.principal': ['Principal', 'เงินต้น'], 'pawn.due': ['Due date', 'ครบกำหนด'], 'pawn.overdue': ['Overdue', 'เกินกำหนด'],
  'pawn.created': ['Contract created', 'ทำสัญญาแล้ว'], 'pawn.month': ['month', 'เดือน'], 'pawn.asOf': ['Calculate as of', 'คำนวณ ณ วันที่'], 'pawn.interestDue': ['Interest due', 'ดอกเบี้ยค้างชำระ'],
  'pawn.redeemTotal': ['Redeem total', 'ยอดไถ่ถอนรวม'], 'pawn.redeem': ['Redeem', 'ไถ่ถอน'], 'pawn.renew': ['Renew (pay interest)', 'ต่อดอก'], 'pawn.payPrincipal': ['Pay part of principal', 'ชำระเงินต้นบางส่วน'],
  'pawn.reduce': ['Reduce principal', 'ลดเงินต้น'], 'pawn.forfeit': ['Mark as forfeited', 'หลุดจำนำ'], 'pawn.forfeitWarn': ['The pledged gold will move into stock and the contract will be closed. This cannot be undone.', 'ทองที่รับจำนำจะถูกย้ายเข้าสต็อกและปิดสัญญา ไม่สามารถย้อนกลับได้'],
  'pawn.forfeited': ['Moved to stock', 'ย้ายเข้าสต็อกแล้ว'], 'pawn.redeemed': ['Redeemed', 'ไถ่ถอนแล้ว'], 'pawn.renewed': ['Renewed', 'ต่อดอกแล้ว'], 'pawn.events': ['History', 'ประวัติ'],
  'pawn.printTicket': ['Print contract', 'พิมพ์สัญญา'], 'pawn.rateMonth': ['Interest % / month', 'ดอกเบี้ย % / เดือน'], 'pawn.termDays': ['Term (days)', 'ระยะเวลา (วัน)'], 'pawn.item': ['Pledged item', 'ทรัพย์ที่รับ'], 'pawn.appraised': ['Appraised value', 'ราคาประเมิน'],
  // savings
  'sav.new': ['Open account', 'เปิดบัญชีออมทอง'], 'sav.acct': ['Account', 'เลขที่บัญชี'], 'sav.plan': ['Plan', 'แผน'], 'sav.mode': ['Saving as', 'รูปแบบการออม'], 'sav.saved': ['Saved', 'ยอดออม'], 'sav.gold': ['Gold (g)', 'ทองสะสม (กรัม)'],
  'sav.opened': ['Account opened', 'เปิดบัญชีแล้ว'], 'sav.open': ['Open account', 'เปิดบัญชี'], 'sav.installment': ['Amount per installment', 'ยอดต่องวด'], 'sav.frequency': ['Frequency', 'รอบการออม'], 'sav.target': ['Target (optional)', 'เป้าหมาย (ไม่บังคับ)'],
  'sav.ticket': ['Gold savings ticket', 'ตั๋วออมทอง'], 'sav.next': ['Next installment', 'งวดถัดไป'], 'sav.deposit': ['Deposit', 'ฝาก'], 'sav.depositAmount': ['Deposit amount', 'ยอดฝาก'], 'sav.deposited': ['Deposited', 'ฝากแล้ว'],
  'sav.close': ['Close account', 'ปิดบัญชี'], 'sav.closeWarn': ['The remaining balance will be refunded and the account closed.', 'ระบบจะคืนยอดคงเหลือและปิดบัญชี'], 'sav.refunded': ['Refunded', 'คืนเงินแล้ว'],
  'sav.history': ['History', 'ประวัติ'], 'sav.printTicket': ['Print ticket', 'พิมพ์ตั๋วออมทอง'],
  // rates
  'rates.current': ['Current price (per baht-weight, 96.5%)', 'ราคาปัจจุบัน (ต่อบาททองคำ 96.5%)'], 'rates.buy': ['We buy', 'รับซื้อ'], 'rates.sell': ['We sell', 'ขายออก'], 'rates.unit': ['per baht-weight (15.244 g) of 96.5% gold', 'ต่อบาททองคำ (15.244 กรัม) ความบริสุทธิ์ 96.5%'],
  'rates.manual': ['Manual', 'ตั้งเอง'], 'rates.byAssoc': ['Association', 'ตามสมาคมฯ'], 'rates.update': ['Update price', 'ปรับราคาทอง'], 'rates.updateHint': ['Enter the prices from the latest association announcement. Bills use the new price immediately; past bills keep theirs.', 'กรอกราคาตามประกาศล่าสุดของสมาคมฯ บิลใหม่จะใช้ราคานี้ทันที บิลเก่าไม่เปลี่ยน'],
  'rates.announcement': ['Announcement no.', 'ประกาศครั้งที่'], 'rates.apply': ['Apply price', 'ใช้ราคานี้'], 'rates.updated': ['Price updated', 'ปรับราคาแล้ว'], 'rates.unchanged': ['Price unchanged', 'ราคาไม่เปลี่ยนแปลง'],
  'rates.history': ['Price history', 'ประวัติราคา'], 'rates.set': ['Set price', 'ตั้งราคา'],
  // reports
  'rep.pl': ['Profit & loss', 'กำไร-ขาดทุน'], 'rep.revenue': ['Sales (ex. VAT)', 'ยอดขาย (ไม่รวม VAT)'], 'rep.cogs': ['Cost of goods sold', 'ต้นทุนสินค้าที่ขาย'], 'rep.gross': ['Gross profit', 'กำไรขั้นต้น'],
  'rep.pawnInterest': ['Pawn interest income', 'ดอกเบี้ยรับ (ขายฝาก/จำนำ)'], 'rep.otherIncome': ['Other income', 'รายได้อื่น'], 'rep.expenses': ['Expenses', 'ค่าใช้จ่าย'], 'rep.net': ['Net profit', 'กำไรสุทธิ'],
  'rep.outputTax': ['Output VAT collected', 'ภาษีขาย'], 'rep.addEntry': ['Add income / expense', 'บันทึกรายรับ-รายจ่าย'], 'rep.category': ['Category', 'หมวดหมู่'], 'rep.categoryHint': ['Rent, salary, utilities…', 'ค่าเช่า, เงินเดือน, ค่าไฟ…'],
  'rep.expense': ['Expense', 'รายจ่าย'], 'rep.income': ['Income', 'รายรับ'], 'rep.ledger': ['Income & expense entries', 'รายการรายรับ-รายจ่าย'], 'rep.etax': ['Revenue Dept. (e-Tax) queue', 'คิวส่งกรมสรรพากร (e-Tax)'],
  'rep.etaxHint': ['Documents waiting to be sent. The connector to the Revenue Department is not set up yet.', 'เอกสารที่รอส่ง ยังไม่ได้เชื่อมต่อระบบกรมสรรพากร'], 'rep.etaxEmpty': ['Nothing waiting', 'ไม่มีเอกสารค้างส่ง'],
  // settings
  'settings.company': ['Company', 'ข้อมูลร้าน'], 'settings.rules': ['Tax & rules', 'ภาษีและกติกา'], 'settings.users': ['Users', 'ผู้ใช้งาน'], 'settings.audit': ['Audit log', 'บันทึกการใช้งาน'],
  'settings.companyInfo': ['Company information', 'ข้อมูลบริษัท / ร้านค้า'], 'settings.nameTh': ['Shop name (Thai)', 'ชื่อร้าน (ไทย)'], 'settings.nameEn': ['Shop name (English)', 'ชื่อร้าน (อังกฤษ)'],
  'settings.taxId': ['Tax ID', 'เลขประจำตัวผู้เสียภาษี'], 'settings.branch': ['Branch code', 'รหัสสาขา'], 'settings.branchHint': ['00000 = head office', '00000 = สำนักงานใหญ่'],
  'settings.address': ['Address', 'ที่อยู่'], 'settings.addressLine': ['House no., building, moo, soi, road', 'เลขที่ อาคาร หมู่ ซอย ถนน'], 'settings.addressLineHint': ['e.g. 123 Yaowarat Rd.', 'เช่น 123 ถนนเยาวราช'],
  'settings.province': ['Province', 'จังหวัด'], 'settings.district': ['District', 'อำเภอ/เขต'], 'settings.subDistrict': ['Sub-district', 'ตำบล/แขวง'], 'settings.postcode': ['Postcode', 'รหัสไปรษณีย์'],
  'settings.choose': ['Select…', 'เลือก…'], 'settings.preview': ['Shown on documents', 'ที่อยู่ที่จะแสดงบนเอกสาร'],
  'settings.logo': ['Company logo', 'โลโก้ร้าน'], 'settings.logoHint': ['PNG, JPEG or WebP. Large images are resized automatically. Shown on bills and invoices.', 'รองรับ PNG, JPEG, WebP ระบบจะย่อรูปให้อัตโนมัติ แสดงบนบิลและใบกำกับภาษี'],
  'settings.noLogo': ['No logo yet', 'ยังไม่มีโลโก้'], 'settings.chooseFile': ['Choose image', 'เลือกรูปภาพ'],
  'settings.tax': ['VAT', 'ภาษีมูลค่าเพิ่ม'], 'settings.taxMode': ['VAT applies to', 'คิด VAT จาก'], 'settings.taxMode.NONE': ['No VAT', 'ไม่คิด VAT'], 'settings.taxMode.MAKING_ONLY': ['Making charges only', 'ค่ากำเหน็จเท่านั้น'], 'settings.taxMode.FULL': ['Whole bill', 'ทั้งบิล'],
  'settings.taxRate': ['VAT rate %', 'อัตรา VAT %'], 'settings.legalNote': ['Please confirm VAT treatment of gold with your accountant.', 'กรุณาตรวจสอบการคิด VAT ของทองกับนักบัญชีของท่าน'],
  'settings.pawnRules': ['Pawn & sell-back', 'ขายฝาก/จำนำ'], 'settings.pawnMax': ['Maximum interest % / month', 'ดอกเบี้ยสูงสุด % / เดือน'], 'settings.pawnTerm': ['Default term (days)', 'ระยะเวลามาตรฐาน (วัน)'],
  'settings.pawnGrace': ['Grace days before forfeit', 'วันผ่อนผันก่อนหลุดจำนำ'], 'settings.pawnMinDays': ['Minimum interest days', 'จำนวนวันขั้นต่ำที่คิดดอกเบี้ย'], 'settings.loyalty': ['Loyalty points', 'แต้มสะสม'], 'settings.bahtPerPoint': ['Baht per 1 point', 'ยอดซื้อ (บาท) ต่อ 1 แต้ม'],
  'settings.addUser': ['Add user', 'เพิ่มผู้ใช้'], 'settings.role': ['Role', 'บทบาท'], 'settings.disable': ['Disable', 'ปิดใช้งาน'], 'settings.enable': ['Enable', 'เปิดใช้งาน'], 'settings.pwHint': ['At least 8 characters', 'อย่างน้อย 8 ตัวอักษร'],
  'settings.action': ['Action', 'การกระทำ'], 'settings.entity': ['Record', 'รายการ'],
  // printing
  'print.title': ['Print', 'พิมพ์'], 'print.print': ['Print', 'พิมพ์'], 'print.download': ['Download HTML', 'ดาวน์โหลด HTML'], 'print.language': ['Document language', 'ภาษาเอกสาร'], 'print.paper': ['Paper', 'ขนาดกระดาษ'], 'print.slip': ['80 mm slip', 'สลิป 80 มม.'],
  // enums
  'st.IN_STOCK': ['In stock', 'ในสต็อก'], 'st.SOLD': ['Sold', 'ขายแล้ว'], 'st.RESERVED': ['Reserved', 'จอง'], 'st.MISSING': ['Missing', 'สูญหาย'], 'st.VOIDED': ['Voided', 'ยกเลิก'], 'st.COMPLETED': ['Completed', 'สำเร็จ'],
  'st.ACTIVE': ['Active', 'ใช้งานอยู่'], 'st.REDEEMED': ['Redeemed', 'ไถ่ถอนแล้ว'], 'st.FORFEITED': ['Forfeited', 'หลุดจำนำ'], 'st.CLOSED': ['Closed', 'ปิดแล้ว'], 'st.ISSUED': ['Issued', 'ออกแล้ว'],
  'st.CANCELLED': ['Cancelled', 'ยกเลิก'], 'st.PENDING': ['Pending', 'รอส่ง'], 'st.SENT': ['Sent', 'ส่งแล้ว'], 'st.FAILED': ['Failed', 'ส่งไม่สำเร็จ'],
  'type.SALE': ['Sale', 'ขาย'], 'type.TRADE_IN': ['Exchange', 'เปลี่ยนทอง'], 'type.BUYBACK': ['Buy-back', 'รับซื้อ'],
  'src.NEW': ['New', 'ใหม่'], 'src.TRADE_IN': ['Customer gold', 'ทองเก่ารับซื้อ'], 'src.FORFEITED': ['Forfeited pawn', 'ทองหลุดจำนำ'],
  'cat.RING': ['Ring', 'แหวน'], 'cat.CHAIN': ['Chain', 'สร้อยคอ'], 'cat.BANGLE': ['Bangle', 'กำไล'], 'cat.PENDANT': ['Pendant', 'จี้'], 'cat.EARRING': ['Earring', 'ต่างหู'], 'cat.BAR': ['Gold bar', 'ทองคำแท่ง'],
  'cat.ORNAMENT': ['Ornament', 'ทองรูปพรรณ'], 'cat.SCRAP': ['Old gold', 'ทองเก่า'], 'cat.FORFEITED': ['Forfeited', 'ทองหลุดจำนำ'],
  'mk.FIXED': ['Fixed amount', 'คงที่ต่อชิ้น'], 'mk.PER_GRAM': ['Per gram', 'ต่อกรัม'], 'mk.PERCENT': ['% of gold value', '% ของค่าทอง'],
  'mth.CASH': ['Cash', 'เงินสด'], 'mth.TRANSFER': ['Transfer', 'โอนเงิน'], 'mth.CARD': ['Card', 'บัตร'], 'mth.SAVINGS': ['Gold savings', 'บัญชีออมทอง'], 'mth.OTHER': ['Other', 'อื่นๆ'],
  'mv.RECEIVE': ['Received', 'รับเข้า'], 'mv.SALE': ['Sold', 'ขายออก'], 'mv.TRADE_IN_RECEIVE': ['Customer gold received', 'รับทองเก่า'], 'mv.FORFEIT_RECEIVE': ['Forfeited into stock', 'รับทองหลุดจำนำ'],
  'mv.VOID_RETURN': ['Returned (void)', 'คืนสต็อก (ยกเลิกบิล)'], 'mv.VOID_REMOVE': ['Removed (void)', 'ตัดออก (ยกเลิกบิล)'], 'mv.ADJUST': ['Adjusted', 'ปรับสถานะ'],
  'dt.TAX_INVOICE_ABBR': ['Abbreviated tax invoice', 'ใบกำกับภาษีอย่างย่อ'], 'dt.TAX_INVOICE_FULL': ['Full tax invoice', 'ใบกำกับภาษีเต็มรูป'], 'dt.PURCHASE_VOUCHER': ['Gold purchase voucher', 'ใบรับซื้อทอง'], 'dt.CREDIT_NOTE': ['Credit note', 'ใบลดหนี้'],
  'pt.PAWN': ['Pawn', 'จำนำ'], 'pt.SELL_BACK': ['Sell-back', 'ขายฝาก'],
  'pe.OPEN': ['Opened', 'ทำสัญญา'], 'pe.RENEW': ['Renewed', 'ต่อดอก'], 'pe.PAY_PRINCIPAL': ['Principal paid', 'ชำระเงินต้น'], 'pe.REDEEM': ['Redeemed', 'ไถ่ถอน'], 'pe.FORFEIT': ['Forfeited', 'หลุดจำนำ'],
  'plan.FIXED': ['Fixed installments', 'รายงวด'], 'plan.FLEXIBLE': ['Flexible', 'อิสระ'], 'mode.CASH': ['Money', 'สะสมเป็นเงิน'], 'mode.GOLD_WEIGHT': ['Gold weight', 'สะสมน้ำหนักทอง'],
  'fr.MONTHLY': ['Monthly', 'รายเดือน'], 'fr.WEEKLY': ['Weekly', 'รายสัปดาห์'], 'sk.DEPOSIT': ['Deposit', 'ฝาก'], 'sk.REDEEM': ['Used to pay', 'ใช้ชำระ'], 'sk.REFUND': ['Refund', 'คืนเงิน'],
  'pr.EARN': ['Earned', 'ได้รับแต้ม'], 'pr.REDEEM': ['Redeemed', 'แลกของรางวัล'], 'pr.ADJUST': ['Adjusted', 'ปรับแต้ม'], 'pr.VOID': ['Reversed', 'ยกเลิกแต้ม'],
  // server error codes
  'err.BAD_CREDENTIALS': ['Wrong username or password', 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'], 'err.NO_RATE': ["Today's gold price has not been set", 'ยังไม่ได้ตั้งราคาทองวันนี้'],
  'err.ITEM_UNAVAILABLE': ['This item is no longer available', 'สินค้านี้ไม่พร้อมขายแล้ว'], 'err.PAYMENT_MISMATCH': ['Payments must equal the amount due', 'ยอดชำระต้องเท่ากับยอดที่ต้องจ่าย'],
  'err.CUSTOMER_REQUIRED': ['A customer is required when buying gold', 'ต้องระบุลูกค้าเมื่อรับซื้อทอง'], 'err.CUSTOMER_ID_REQUIRED': ["The customer's national ID is required", 'ต้องมีเลขบัตรประชาชนของลูกค้า'],
  'err.FORBIDDEN': ['You do not have permission for this', 'คุณไม่มีสิทธิ์ทำรายการนี้'], 'err.RATE_TOO_HIGH': ['Interest rate is above the allowed maximum', 'อัตราดอกเบี้ยสูงกว่าที่กำหนด'],
  'err.NOT_OVERDUE': ['This contract is not overdue yet', 'สัญญานี้ยังไม่เกินกำหนด'], 'err.INSUFFICIENT_SAVINGS': ['Not enough savings for this payment', 'ยอดออมทองไม่พอสำหรับการชำระนี้'],
  'err.INSUFFICIENT_POINTS': ['Not enough points', 'แต้มไม่พอ'], 'err.OUT_OF_STOCK': ['Reward is out of stock', 'ของรางวัลหมด'],
  'err.SELLER_NOT_CONFIGURED': ['Set the company tax ID in Settings first', 'กรุณาตั้งเลขประจำตัวผู้เสียภาษีของร้านในตั้งค่าก่อน'], 'err.VOID_BLOCKED': ['Cannot void: items from this bill were already resold', 'ยกเลิกไม่ได้: สินค้าจากบิลนี้ถูกขายต่อไปแล้ว'],
  'err.ALREADY_VOIDED': ['This bill is already voided', 'บิลนี้ถูกยกเลิกแล้ว'], 'err.INVALID_LOGO': ['Logo must be a valid PNG, JPEG or WebP image', 'โลโก้ต้องเป็นรูป PNG, JPEG หรือ WebP'],
  'err.LOGO_TOO_LARGE': ['Logo is too large (max 400 KB)', 'ไฟล์โลโก้ใหญ่เกินไป (สูงสุด 400 KB)'], 'err.INVALID_AREA': ['The sub-district does not match the district / province', 'ตำบล อำเภอ จังหวัด ไม่สอดคล้องกัน'],
  'err.DUPLICATE_SKU': ['This SKU already exists', 'รหัสสินค้านี้มีอยู่แล้ว'], 'err.DUPLICATE': ['Already exists', 'มีอยู่แล้ว'], 'err.NOT_FOUND': ['Not found', 'ไม่พบข้อมูล'],
  'err.BUYER_REQUIRED': ['Buyer name, tax ID and address are required', 'ต้องระบุชื่อ เลขผู้เสียภาษี และที่อยู่ผู้ซื้อ'], 'err.INVALID_STATE': ['Not allowed in the current state', 'ทำรายการนี้ไม่ได้ในสถานะปัจจุบัน'],
  'err.VALIDATION': ['Please check the form fields', 'กรุณาตรวจสอบข้อมูลที่กรอก'],
} satisfies Record<string, [string, string]>;

export type Key = keyof typeof DICT;
